---
- name: become root and install shadowsocks
  ansible.builtin.import_tasks: root.yml
  become: true
  when: wrt_ss_enable |bool
  tags: wrt_ss_all

- name: run postponed handlers now
  ansible.builtin.meta: flush_handlers
...
