---
## handlers for ivansible.entware.v2ray

- name: remove temporary v2ray client directory
  ansible.builtin.file:
    path: "{{ temp_v2ray_client_dir.path }}"
    state: absent
  become: true

- name: restart wrt service v2ray
  ivansible.entware.openwrt_init2:
    name: "{{ wrt_v2ray_initd }}"
    state: restarted
  tags: skip_ansible_lint
  become: true
...
