---
## handlers for ivansible.entware.wireguard

- name: restart wrt service wireguard
  ivansible.entware.openwrt_init2:
    name: "{{ wrt_wg_initd }}"
    state: restarted
  tags: skip_ansible_lint
  become: true
...
