---
- name: become root and setup network routing
  ansible.builtin.import_tasks: root.yml
  become: true
  tags: wrt_net_all

- name: add netfilter shell helpers for user
  ansible.builtin.blockinfile:
    path: "{{ ansible_user_dir }}/.profile"
    block: "{{ lookup('template', 'shell-helpers.sh') }}"
    marker: '# {mark} NETFILTER SHELL HERLPERS'
    create: true
    mode: 0644
  tags:
    - wrt_net_user
    - wrt_net_all

- name: run postponed handlers now
  ansible.builtin.meta: flush_handlers
  tags: wrt_net_all
...
