---
namespace: ivansible
name: entware
version: 1.0.0

description: Ansible collection for Keenetic Entware

authors:
  - Ivan Andreev <ivandeex@gmail.com>

tags:
  - keenetic
  - entware
  - openwrt
  - netfilter
  - routing
  - socks
  - vpn
  - openvpn
  - wireguard
  - yggdrasil

# https://python-semanticversion.readthedocs.io/en/latest/#requirement-specification
# namespace.name: version_range
dependencies: {}

repository: https://github.com/ivansible/entware
documentation: https://github.com/ivansible/entware
homepage: https://github.com/ivansible/entware
issues: https://github.com/ivansible/entware/issues

readme: README.md
license: MIT

build_ignore:
  - '*.pyc'
  - '*.tar'
...
