---
- name: install core packages
  community.general.opkg:
    name: "{{ wrt_core_packages |join(',') }}"
  tags: wrt_core_packages

- name: configure ssh
  ansible.builtin.import_tasks: ssh.yml
  tags: wrt_core_ssh

- name: configure user environment
  ansible.builtin.import_tasks: user.yml
  tags: wrt_core_user

- name: setup swap space
  ansible.builtin.import_tasks: swap.yml
  when:
    - wrt_swap_size_mb |int > 0
    - wrt_swap_file |d('')
  tags: wrt_core_swap
...
