---
- name: activate swap file on every boot
  ansible.builtin.template:
    src: swapon.init.sh
    dest: /opt/etc/init.d/S99swapon
    mode: 0755

- name: setup and activate swap file
  ansible.builtin.command:
    cmd: /opt/etc/init.d/S99swapon start
    creates: "{{ wrt_swap_file }}"
...
