---
- name: add shell aliases for user
  blockinfile:
    path: "{{ ansible_user_dir }}/.profile"
    block: |
      {% for alias in wrt_shell_aliases |dictsort %}
      alias {{ alias.0 }}='{{ alias.1 }}'
      {% endfor %}
    ## 'dummy quote to fix vim highliter
    marker: '# {mark} ANSIBLE SHELL ALIASES'
    create: true
    mode: 0644

- name: customize tmux for user
  lineinfile:
    path: "{{ ansible_user_dir }}/.tmux.conf"
    line: "{{ item }}"
    create: true
    mode: 0644
  loop:
    - 'set-option -g history-limit 22000'
    - 'bind -n C-k clear-history'  # clear scroll buffer on Ctrl-K
    - 'bind -n C-u copy-mode -u'   # show scroll buffer on Ctrl-U
    - 'new-session'                # auto-create new sessions
...
