---
- name: setup and enable supervisor
  ansible.builtin.import_tasks: root.yml
  become: true
  when: wrt_use_supervisor |bool
  tags: wrt_supervisor_all

- name: run postponed handlers now
  ansible.builtin.meta: flush_handlers
...
