---
- name: check for existing supervisord
  ansible.builtin.stat:
    path: /opt/bin/supervisord
  register: stat_supervisord

- name: install supervisor
  ansible.builtin.pip:
    name: supervisor
    state: present
    executable: pip3
  when: not stat_supervisord.stat.exists

- name: create supervisor config directory
  ansible.builtin.file:
    path: /opt/etc/supervisord.d
    state: directory
    mode: 0755

- name: create supervisor log directory
  ansible.builtin.file:
    path: /opt/var/log/supervisord
    state: directory
    mode: 0755

- name: create supervisor config file
  ansible.builtin.template:
    src: supervisord.conf
    dest: /opt/etc/supervisord.conf
    mode: 0644
  notify: restart wrt service supervisord

- name: create supervisor startup script
  ansible.builtin.copy:
    src: supervisord.rc.sh
    dest: /opt/etc/init.d/{{ wrt_supervisor_initd }}
    mode: 0755
    force: true
  notify: restart wrt service supervisord

- name: enable wrt service supervisord
  ivansible.entware.openwrt_init2:
    name: "{{ wrt_supervisor_initd }}"
    state: started
  tags: skip_ansible_lint
...
