---
# handlers for ivansible.wrt_sshtun

- name: restart wrt service sshtun
  ivansible.entware.openwrt_init2:
    name: "{{ wrt_sshtun_initd }}"
    state: restarted
  tags: skip_ansible_lint
  become: true
...
