---
## handlers for ivansible.entware.ss

- name: remove temporary v2ray plugin directory
  ansible.builtin.file:
    path: "{{ temp_v2ray_plugin_dir.path }}"
    state: absent
  become: true

- name: restart wrt service shadowsocks
  ivansible.entware.openwrt_init2:
    name: S22shadowsocks
    state: restarted
  tags: skip_ansible_lint
  become: true
...
