---
- name: install v2ray client as root
  ansible.builtin.import_tasks: root.yml
  become: true
  when: wrt_v2ray_enable |bool
  tags: wrt_v2ray_all

- name: run postponed handlers now
  ansible.builtin.meta: flush_handlers
...
