---
- name: install srelay as root
  ansible.builtin.import_tasks: root.yml
  become: true
  when: wrt_srelay_enable |bool
  tags: wrt_srelay_all

- name: run postponed handlers now
  ansible.builtin.meta: flush_handlers
...
