---
- name: setup ssh tun client as root
  ansible.builtin.import_tasks: root.yml
  become: true
  when:
    - wrt_sshtun_enable |bool
    - wrt_sshtun_servers |d([])
    - wrt_sshtun_default_server |d('')
  tags: wrt_sshtun_all

- name: run postponed handlers now
  ansible.builtin.meta: flush_handlers
  tags: wrt_sshtun_all
...
