---
- name: become root and setup wireguard
  ansible.builtin.import_tasks: root.yml
  become: true
  when: wrt_wg_nets |d([])
  tags:
    - wrt_wg_all
    - wrt_wireguard_all

- name: run postponed handlers now
  ansible.builtin.meta: flush_handlers
  tags:
    - wrt_wg_all
    - wrt_wireguard_all
...
