---
- name: become root and setup openvpn
  ansible.builtin.import_tasks: root.yml
  become: true
  when:
    - wrt_ovpn_servers |d([])
    - wrt_ovpn_default_server |d('')
  tags:
    - wrt_ovpn_all
    - wrt_openvpn_all

- name: run postponed handlers now
  ansible.builtin.meta: flush_handlers
  tags:
    - wrt_ovpn_all
    - wrt_openvpn_all
...
