---
## handler for ivansible.entware.yggdrasil
## (copy-pasted from ivansible.entware.net)

- name: restart wrt service routing (yggdrasil)
  ivansible.entware.openwrt_init2:
    name: "{{ wrt_net_initd }}"
    state: restarted
  tags: skip_ansible_lint
  become: true
...
